[package]
name = "brouwerfixedpoint"
version = "0.1"
lean_version = "leanprover-community/lean:3.30.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/Eloitor/mathlib", rev = "09db37a8f7e6d9f9b752e6e3750d8347c1269039"}
